name: CI/CD

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run build
        run: mvn clean package -DskipTests
      - name: Run tests
        run: mvn clean verify
  build_and_deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Set image name
        id: set_image_name
        run: echo "IMAGE_NAME=mateuszjanczak/agent:$(date +%s)" >> $GITHUB_OUTPUT
      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ steps.set_image_name.outputs.IMAGE_NAME }} --tag latest
      - name: Push image
        run: docker image push --all-tags mateuszjanczak/agent
      - name: Deploy image
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl --write-out '%{http_code}' --silent --output /dev/null $DEPLOY_URL
