name: CI/CD

on:
  push:
    branches: [ "19-setup-cicd-pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run build
        run: mvn clean package -DskipTests
      - name: Run tests
        run: mvn clean verify